### ISSUE TITLE
Importing UTF-8 CSV

### ISSUE THREAD

**Issue by gatokichi** [pklink/ppma#43]
I imported UTF-8 CSV into the ppma.
Imported results looks normal, but imported entries values are empty after re-login. 
encryptedPassword values broke.

**Comment by pklink** [comment]
Can you provide an example file, please? I tried it with the following files and had no problems:

http://a.pomf.se/oloqtk.zip

**Comment by gatokichi** [comment]
When I did a retest today, it wasn't possible to make them recur.
I'd like to retract this ticket.
