### ISSUE TITLE
Can't delete entries or TAGs

### ISSUE THREAD

**Issue by luizlinux** [pklink/ppma#44]
Whenever I need to delete an entry or a tag the php(?) code fails to render a proper html output resulting in a broken page.
See attached screenshot for details.

This happens to any of the entries I have.
Another odd thing I noticed is that the text always reads "Delete Tag" even when I try to delete an entry and not a tag.
![2015-02-04_12-19-24](https://cloud.githubusercontent.com/assets/10618435/6041980/484ead8e-ac68-11e4-946f-6c168bb36db8.png)

**Comment by luizlinux** [comment]
Forgot to mention running version:
* ppma (version 0.5.0) powered by yii framework (version 1.1.15) and Foundation 3 (version 3.2)
AKA the pre-built zip file.

**Comment by deoren** [comment]
Same here with the same version installed.

**Comment by pklink** [comment]
Thanks for the messages. It should be working with the latest release: https://github.com/pklink/ppma/releases/tag/0.5.1
