### ISSUE TITLE
RFE: Add support for alternate database host port

### ISSUE THREAD

**Issue by deoren** [pklink/ppma#46]
I tried appending `:3307` to the `server` variable like this:

```php
<?php
return array (
  'db' => 
  array (
    'server' => '127.0.0.1:3307',
    'username' => 'root',
    'password' => 'password',
    'name' => 'ppma',
  ),
  'isInstalled' => false,
  'version' => '0.5.1',
);
```

and also adding a new entry to the array like this:

```php
<?php
return array (
  'db' => 
  array (
    'server' => '127.0.0.1',
    'port' => '3307',
    'username' => 'root',
    'password' => 'password',
    'name' => 'ppma',
  ),
  'isInstalled' => false,
  'version' => '0.5.1',
);
```

The first resulted in an immediate error, the second just wasn't honored. Am I overlooking something or is this just not supported (yet)?

Thanks!

**Comment by pklink** [comment]
It's not really supported atm. As quick-dirty-solution you can try this:

```php
<?php
return array (
  'db' => 
  array (
    'server' => '127.0.0.1;port=3307',
    'username' => 'root',
    'password' => 'password',
    'name' => 'ppma',
  ),
  'isInstalled' => false,
  'version' => '0.5.1',
);
```

In version 0.6.0 will your 2nd code snippet work.

**Comment by deoren** [comment]
@pklink awesome, thanks! I'll give that a try. Thanks in advance for adding this feature.
