### ISSUE TITLE
tried the 1.0 branch but no luck

### ISSUE THREAD

**Issue by XaRz** [pklink/ppma#62]
Hello,

After checking the 0.5.1 version I noticed the branch 1.0.0. I've tried but i'm receiving this:
![phppasswords_1](https://cloud.githubusercontent.com/assets/6230850/13885328/1a91b826-ed32-11e5-8642-5d623b001d19.png)

Perhaps is my lack of knowledge, if it's so, my excuses in advance

PS: I've compiled in a joomla vagrant box in a macosx (joomlatools vagrant box: https://www.joomlatools.com/developer/tools/vagrant/) but I've followed the installation step till last: 
php -S localhost:8080 -t ./public/ (I've not used because I've the server going on the vagrant box. I've copied the ppma folder to my /var/www/ppma1 and I tried browsing http://joomla.box/ppma1/public/index.php with that result.

I'm doing something wrong?

Regards.

**Comment by pklink** [comment]
Hi,

the 1.0.0-branch is still under development and doesn't work atm.

Regards, Pierre

**Comment by XaRz** [comment]
Oh, ok then. There is any place pointing the features of the 1.0 version?

I'm being hyped :dancer: 

thanks for your efforts. Regards.
