### ISSUE TITLE
Installation all green, but next button does nothing

### ISSUE THREAD

**Issue by rolfkunst** [pklink/ppma#68]
Hi Everyone,
I try to install ppma, but I run into a problem immediately. It's stuck at the first step. All is green, PHP-Version, php5-mcrypt, php5-pdo, php5-pdo_mysql. And the persmissions assets, runtime ppma.php, all green. When I hit the Next >> button, it does something, but returns to the same page.

I have:
IIS 8.0
PHP version: 5.6.16
MySQL version: 5.7.11

What can I do to resolve it?

Thanks in advance!

With regards,
Rolf Kunst

**Comment by rolfkunst** [comment]
Hi pklink,

Thank you for your quick response!

I've overwritten the file original file with the file you provided, but unfortunately without results. It is still the same, all green, but next button seems to refresh the page. I've tried to disable some php features just to see if it turns red, and it does.

Do you have any suggestions?

With regards,
Rolf Kunst

**Comment by pklink** [comment]
Change your `index.php` to this and try it again, please:

```php
<?php

// remove the following lines when in production mode
defined('YII_DEBUG') or define('YII_DEBUG',true);
defined('YII_TRACE_LEVEL') or define('YII_TRACE_LEVEL',3);

// change the following paths if necessary
$yii    = dirname(__FILE__) . '/vendor/yiisoft/yii/framework/yii.php';
$config = dirname(__FILE__) . '/protected/config/main.php';
// $config=dirname(__FILE__).'/protected/config/test.php'; // for testing

/** @noinspection PhpIncludeInspection */
require_once($yii);
Yii::createWebApplication($config)->run();

```

Are there any entries in your php error log or in `protected/runtime/application.log` now?

**Comment by rolfkunst** [comment]
Hi,

Thanks again for your quick response. I have only some info from application.log PHP log is clean:

```
2016/06/03 12:20:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "step2".' in E:\_Websites\test\vendor\yiisoft\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\_Websites\test\vendor\yiisoft\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('step2')
#1 E:\_Websites\test\vendor\yiisoft\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\_Websites\test\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=step2
---
2016/06/03 12:20:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "step_2".' in E:\_Websites\test\vendor\yiisoft\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\_Websites\test\vendor\yiisoft\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('step_2')
#1 E:\_Websites\test\vendor\yiisoft\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\_Websites\test\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=step_2
---

```

**Comment by rolfkunst** [comment]
And that is what I typed self in the URI

**Comment by pklink** [comment]
Do you clear your browser cache? Can you post your `php.ini`, please?

**Comment by rolfkunst** [comment]
[php - Copy.txt](https://github.com/pklink/ppma/files/297403/php.-.Copy.txt)
I have cleared my cache, but without results.
I have attached my php.ini as php - copy.txt

**Comment by pklink** [comment]
change the following settings and check your php_log again

```ini
error_reporting = E_ALL
display_errors = On
display_startup_errors = On
track_errors = On
```

**Comment by rolfkunst** [comment]
Hi, I found out what it was, I had (don't know why) multiple instances of php cgi. I deleted every which was unused, as far as I know, and it is working now!
I will disable logging again.
Thank's for your time and hints!

With regards,
Rolf Kunst

**Comment by pklink** [comment]
nice to hear that ;-)
