### ISSUE TITLE
Regd. Fetching of Records

### ISSUE THREAD

**Issue by trascemd** [pklink/ppma#83]
Hi,

Application is very nice & has great GUI (Look & Feel is good).

Created user from backend, all is working fine but when I log in as admin & check the entries created by USER not able to view the full details .

In DASHBOARD can see the record names in list but when I click the form is empty without data same for UPDATE also but can see the record details created by Admin........User not able to see is fine but can view records created by USER only......

What can be done to view all the record details when someone is logged in as ADMIN.

Appreciate the help in resolving the issue.

Thanks,
Nick

**Comment by pklink** [comment]
Hi Nick,

atm ppma doesn't support multiple users. Do you download the your version from this repository?

Regards, Pierre

**Comment by trascemd** [comment]
Hi Pierre,

Thanks for the response.

Not sure from where I downloaded as I was looking for similar product like things & tried lot other products but liked this one...so not sure..

Version what I have is 0.6.0.

Is there anyway with this 0.6.0 version where we can have admin access all the records...

Thanks,
Nick

**Comment by pklink** [comment]
Hi Nick!

Nop, this is not possible. The encryption key is different for every user and depends on the individually user password
