### ISSUE TITLE
https://sourceforge.net/projects/ppma/ is down

### ISSUE THREAD

**Issue by MagicFab** [pklink/ppma#89]
The READM / main project page has this section:

**More info / screenshots**
You can find more info and screenshots at http://sourceforge.net/projects/ppma/

Unfortunately the site is down.

**Comment by pklink** [comment]
fixed with 552a7fbeb01b18a12aef5a7a44573e97ed9d60b3

thank you!

**Comment by MagicFab** [comment]
The link was removed from the main page but the site remains down. Is there another URL to replace it and see screenshots etc.?

**Comment by MagicFab** [comment]
I also file #88 - was this the same site?

**Comment by pklink** [comment]
This project is inactive. So there are no screenshots available on the project sites, sorry. 

The source forge project was removed and this repo is still existing as "archive".

**Comment by pklink** [comment]
I've added an inactive tag to the project description

**Comment by MagicFab** [comment]
Sorry to hear, thanks for all the quick updates.
